### ISSUE TITLE
Explore graceful handling of unexpected responses for consuming packages

### ISSUE THREAD

**Issue by stevenmaguire** [jobapis/jobs-common#18]
In issue #17 a behavior was observed where the API returned an unexpected response and the remaining logic attempted to execute and failed. I am interested in exploring a pattern wherein the common package can handle these cases and defer responsibility to the implementing package.

**Comment by karllhughes** [comment]
I saw this crop up again in v2. A user got an exception like this using the Indeed provider when it returned no results:

```
Warning: array_map(): An error occurred while invoking the map callback in Project\vendor\jobapis\jobs-common\src\Providers\AbstractProvider.php on line 214
```

In the `getJobsCollectionFromListings` method I was assuming that each item actually had content, but it turns out some providers will return an array with one array inside. So, I added a method and conditional for this Indeed case.

A better solution long-term may be wrapping some of this in a `try/catch` within the package. I'll monitor this issue and see if that is warranted.
